[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"
nixpacksVersion = "1.0.0"

[phases.setup]
nixPkgs = ["nodejs@18"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"
PORT = "3000"
NODE_VERSION = "18.x" 